version: "3.9"  # Docker Compose 최신 버전
services:
  spark-master:
    image: bitnami/spark:latest # 이미지 버전은 하둡같은 라이브러리와 함께 쓸때 지정(현재 최신버전)
    environment:
      - SPARK_MODE=master # 클러스터 역할 : 중앙관리 마스터
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
# 그 외의 속성들을 추가해서 구현하기
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network


#  spark-worker-2: #추가 작업수행 노드가 필요할때 주석지우기
#    image: bitnami/spark:latest
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark-master:7077
#    depends_on:
#      - spark-master
#    networks:
#      - spark-network
networks:
  spark-network:
    driver: bridge